!!python/object:argparse.Namespace
data: !!python/object:argparse.Namespace
  dataset: Sorting
  dataset_length: 1000
  fit_intermediate: true
  n: 10
  num_workers: 0
  save_sparsity_mask: false
  sparsity_mask_index: 2
  test_dataset_length: 100
device: !!python/object/apply:torch.device
- cuda
diffusion: !!python/object:argparse.Namespace
  beta_end: 0.005
  beta_schedule: linear
  beta_start: 0.0001
  num_diffusion_timesteps: 1000
model: !!python/object:argparse.Namespace
  attn_dim_reduce: 1
  conditional: fixed
  ema: true
  ema_rate: 0.5
  emb_dim: 64
  impose_sparsity: sparse
  n_heads: 1
  num_transformers: 6
  predict: x0
  resnet: true
  softmax: true
  type: simple
  var_embedding: true
  var_type: fixedlarge
optim: !!python/object:argparse.Namespace
  amsgrad: false
  beta1: 0.9
  eps: 1.0e-08
  grad_clip: 1.0
  lr: 0.0002
  optimizer: Adam
  weight_decay: 0.0
sampling: !!python/object:argparse.Namespace
  sampling_batch_size: 16
training: !!python/object:argparse.Namespace
  batch_size: 16
  max_epoch_iters: 1000
  mean_latents_loss: false
  n_epochs: 60
  snapshot_freq: 20000
